# Generated by Django 3.2 on 2021-10-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geeksmodel',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='geeksmodel',
            name='countInStock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
