# Generated by Django 3.2 on 2021-10-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20211026_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geeksmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
